### ISSUE TITLE
Incomming MQTT message

### ISSUE THREAD

**Issue by OlafTheSnowman** [jgeisler0303/can2mqtt#1]
Hi jgeisler0303,

my incomming MQTT message couldn't be parsed:

2017-03-01 22:07:56,499 ERROR:Error translating mqtt message "601,2B,10,17,00,00,02,00,00" from topic "/CANopen/ID1_PHB" via transmitter transmitter_0: Error collecting values: 'cand_id'

My transmitter section look like this:
    transmitters: [
        {
            subscriptions: "/CANopen/ID1_PHB",
            canid: "can_id",
            pack_template: "BBBBBBBBB",
            var_names: ["cand_id", "val0", "val1", "val2", "val3", "val4", "val5", "val6", "val7"],
            topic_template: "",
            payload_template: "{can_id:d},{val0:d},{val1:d},{val2:d},{val3:d},{val4:d},{val5:d},{val
        },
    ]

May be you can give me a hint about this? 

Thank you

Olaf

PS: Receivers side is working well.

**Comment by jgeisler0303** [comment]
When parsing the MQTT payload the first value is named `can_id` which is used as the CAN message ID. The var_name `cand_id` (notice the extra "d") is not defined during parsing the MQTT payload. Maybe this is a typo?

**Comment by OlafTheSnowman** [comment]
You are right this is a typo, this should be `can_id` (may be better `cob_id`).
The incoming MQTT telegram is a general CAN SDO telegram like "601,2B,10,17,00,00,02,00,00",
in this case to turn on producer heartbeat for device ID1. I hope I understood correct - 
the payload_template is to parse the incoming MQTT telegram - pack_template is used to format
the CAN telegram?
The SDO telegram transmitted via commandline `cansend 601#2B10170000020000` is
formatted cob_id#b0b1b2b3b4b5b6b7. Do I have to use at `pack_template` 9 characters (with can_id)
or 8 characters (without can_id)?

**Comment by jgeisler0303** [comment]
Yes,  payload_template is to parse the incoming MQTT telegram and pack_template together with var_names defines the CAN message body (excluding the CAN ID). CAN ID is taken from the canid configuration parameter and can either be a number or a variable named in the payload_template. The message is then assembled like `canid#payload_template`.

What are you using mqtt2can for, if I may ask?

**Comment by OlafTheSnowman** [comment]
OK, this information from you was the breakthrough :-) From the example config I couldn't see that I have to exclude the can_id from var_names. Transmisson side is now running too! The CAN telegram is traced by candump.

I want to setup my homeautomation with can2mqtt, some years ago I installed an used OMRON PLC and now I'm afraid it could break down. So want to use a WAGO CANopen coupler with digital I/Os for it. The new setup is OpenHAB2 <-> Mosquitto <-> can2mqtt <-> CAN controller(MCP2515)@raspiberry pi <-> WAGO 750 series. 

Thank you very much.
