### ISSUE TITLE
transmitters functionality

### ISSUE THREAD

**Issue by OlafTheSnowman** [jgeisler0303/can2mqtt#2]
Dear jgeisler0303,

when there is a mqtt tramit telegram to can-bus the last byte is fix 0x00. 

e.g.

mqtt command:
mosquitto_pub -t '/CANopen/ID1_RxPDO1' -m '0x201,0xFF,0xFF,0xFF,0x55'

candump result:
can0  201   [4]  FF FF FF 00

it should be:
can0  201   [4]  FF FF FF 55

my configuration:

    transmitters: [
        {
            subscriptions: "/CANopen/ID1_RxPDO1",
            canid: "cob_id",
            pack_template: "BBBB",
            var_names: ["val1", "val2", "val3", "val4"],
            topic_template: "",
            payload_template: "{cob_id:d},{val1:d},{val2:d},{val3:d},{val4:d}"
        },

Please can you check this?

Best regards

**Comment by jgeisler0303** [comment]
Somehow the parse class I'm using doesn't like the last hex number. It doesn't know where it ends. But there are at least two ways around it:
* Use `payload_template: "{cob_id:d},{val1:d},{val2:d},{val3:d},{val4:d},"` and terminate every message with a comma.
* Use `payload_template: "{cob_id:x},{val1:x},{val2:x},{val3:x},{val4:x}"`. Then it works with and without leading "0x", so you could omit them. But decimal integers don't work any more.

**Comment by OlafTheSnowman** [comment]
Thank you, both solutions are working fine.
